/* ====================== EXERCISE LIBRARY (pre-loaded) ====================== */
export const EXERCISE_DB = {
  Petto: ["Panca Piana Bilanciere", "Panca Piana Manubri", "Panca Inclinata Bilanciere", "Panca Inclinata Manubri", "Panca Declinata", "Chest Press", "Croci Manubri", "Croci ai Cavi", "Pectoral Machine", "Push-Up", "Dip alle Parallele", "Panca Piana Smith Machine", "Panca Inclinata Smith Machine", "Croci Cavi dal Basso", "Croci Cavi dall'Alto", "Croci Manubri su Inclinata", "Dip Machine", "Push-Up Zavorrati", "Chest Press Presa Stretta", "Panca Piana con Fermi", "Chest Fly Macchina", "Floor Press", "Croci ai Cavi su Panca"],
  Dorso: ["Trazioni", "Trazioni Presa Inversa", "Lat Machine Avanti", "Lat Machine Presa Stretta", "Rematore Bilanciere", "Rematore Manubrio", "Rematore T-Bar", "Pulley Basso", "Pull-Down Braccia Tese", "Hyperextension", "Stacco da Terra", "Pull-Up Assistito", "Lat Machine Presa Inversa", "Rematore Chest Support", "Rematore Smith Machine", "Rematore Pendlay", "Pullover Manubrio", "Pullover ai Cavi", "Rack Pull", "Good Morning", "Trazioni Presa Larga", "Seated Row", "Lat Machine Presa Neutra", "Seal Row", "Meadows Row", "Lat Prayer"],
  Gambe: ["Squat Bilanciere", "Front Squat", "Leg Press", "Hack Squat", "Affondi Manubri", "Affondi Bulgari", "Stacco Rumeno", "Leg Extension", "Leg Curl Sdraiato", "Leg Curl Seduto", "Hip Thrust", "Calf Raise in Piedi", "Calf Raise Seduto", "Squat Smith Machine", "Goblet Squat", "Stacco Sumo", "Affondi in Camminata", "Leg Curl in Piedi", "Adductor Machine", "Abductor Machine", "Glute Bridge", "Box Step-Up", "Calf Raise alla Pressa", "Squat con Fermi", "Stacco Rumeno con Manubri", "Bulgarian Split Squat Smith Machine", "Belt Squat", "Sissy Squat", "Nordic Hamstring Curl", "Wall Sit"],
  Spalle: ["Military Press", "Shoulder Press Manubri", "Arnold Press", "Alzate Laterali", "Alzate Laterali ai Cavi", "Alzate Frontali", "Alzate Posteriori", "Face Pull", "Shrug Bilanciere", "Military Press Seduto", "Shoulder Press Machine", "Alzate Laterali Macchina", "Alzate Laterali Seduto", "Reverse Pec Deck", "Tirate al Mento", "Alzate Frontali ai Cavi", "Shrug Manubri", "Rear Deltoid", "Rear Delt Fly", "Lu Raises", "Y-Raise"],
  Bicipiti: ["Curl Bilanciere", "Curl Manubri Alternato", "Curl Panca Scott", "Hammer Curl", "Curl ai Cavi", "Curl Concentrato", "Spider Curl", "Curl Bilanciere EZ", "Curl su Panca Inclinata", "Curl Macchina", "Curl Presa Inversa", "Zottman Curl", "Hammer Curl ai Cavi", "Bayesian Curl", "Preacher Curl Manubri", "Drag Curl"],
  Tricipiti: ["Pushdown Tricipiti", "Pushdown Corda", "French Press", "Estensioni Sopra la Testa", "Panca Presa Stretta", "Dip tra Panche", "Kickback Manubrio", "French Press Manubri", "Pushdown Presa Inversa", "Pushdown Braccio Singolo", "Kickback ai Cavi", "Estensione Singola Sopra la Testa", "Dip Machine Tricipiti", "Skull Crusher", "Overhead Cable Extension", "JM Press", "Tate Press"],
  Core: ["Plank", "Crunch", "Crunch ai Cavi", "Russian Twist", "Leg Raise", "Hanging Leg Raise", "Ab Wheel", "Side Plank", "Crunch Inverso", "Crunch su Panca Declinata", "Sit-Up", "Mountain Climbers", "Dead Bug", "Hollow Hold", "Toes to Bar", "Pallof Press", "Ab Crunch Machine", "V-Up", "Bicycle Crunch", "Hanging Knee Raise", "Cable Woodchopper", "Dragon Flag"],
  Cardio: ["Corsa", "Camminata Veloce", "Tapis Roulant", "Cyclette", "Ellittica", "Vogatore", "Salto della Corda", "Stepper", "Camminata in Salita", "Sprint", "Nuoto", "Assault Bike", "Spin Bike", "Burpees", "Jumping Jack", "Sacco da Boxe", "Battle Ropes", "SkiErg", "Stairmaster"],
};
export const GROUPS = Object.keys(EXERCISE_DB);
export const findGroup = (name) => {
  const n = name.toLowerCase();
  for (const [g, list] of Object.entries(EXERCISE_DB))
    if (list.some((e) => e.toLowerCase() === n)) return g;
  return "Altro";
};


/* ---------------- Descrizioni esecuzione esercizi ---------------- */
export const EXERCISE_INFO = {
  "Panca Piana Bilanciere": "Sdraiati sulla panca con scapole addotte e piedi a terra. Impugna il bilanciere poco oltre le spalle, scendi controllato fino a sfiorare il petto e spingi verso l'alto senza bloccare i gomiti. Mantieni i glutei sulla panca.",
  "Panca Inclinata Bilanciere": "Panca a 30-45°. Scendi con il bilanciere verso la parte alta del petto e spingi in verticale. Enfatizza la porzione clavicolare del pettorale.",
  "Chest Press": "Regola il sedile con le maniglie all'altezza del petto. Spingi in avanti senza estendere completamente i gomiti e torna lento in apertura mantenendo tensione.",
  "Croci Manubri": "Sdraiato, braccia semiflesse e fisse. Apri i manubri ad arco fino ad avvertire allungamento sul petto, poi richiudi come per abbracciare. Movimento ampio, carichi moderati.",
  "Push-Up": "Mani poco oltre le spalle, corpo in linea dalla testa ai talloni. Scendi con il petto verso terra tenendo i gomiti a ~45° e spingi su senza inarcare la schiena.",
  "Dip alle Parallele": "Sospeso alle parallele, busto leggermente inclinato avanti per il petto. Scendi finché le spalle sono poco sotto i gomiti e risali spingendo. Fermati prima se avverti fastidio alle spalle.",
  "Trazioni": "Presa prona poco oltre le spalle. Parti da braccia distese, tira il petto verso la sbarra portando i gomiti in basso e indietro, scendi controllato senza slanci.",
  "Lat Machine Avanti": "Impugna larga la sbarra, busto leggermente indietro. Tira verso l'alto del petto pensando a spingere i gomiti in basso, risali frenando il carico.",
  "Rematore Bilanciere": "Busto inclinato ~45° con schiena neutra e core attivo. Tira il bilanciere verso l'ombelico tenendo i gomiti vicini al corpo, scendi controllato.",
  "Pulley Basso": "Seduto, gambe semiflesse e schiena dritta. Tira la maniglia verso l'addome stringendo le scapole, torna avanti allungando senza incurvare la schiena.",
  "Stacco da Terra": "Piedi sotto il bilanciere, schiena neutra, petto in fuori. Spingi il pavimento con le gambe e sali estendendo anche e ginocchia insieme, bilanciere aderente al corpo. Tecnica prima del carico.",
  "Squat Bilanciere": "Bilanciere sui trapezi, piedi poco oltre le spalle. Scendi spingendo le anche indietro e le ginocchia in linea con le punte fino a cosce parallele (o sotto), risali spingendo con tutto il piede.",
  "Leg Press": "Piedi al centro della pedana alla larghezza spalle. Scendi controllato fino a ~90° senza staccare il bacino dallo schienale, spingi senza bloccare le ginocchia.",
  "Affondi Manubri": "Passo avanti ampio, scendi in verticale finché il ginocchio posteriore sfiora terra. Il ginocchio anteriore resta in linea con il piede. Spingi con il tallone per risalire.",
  "Stacco Rumeno": "Gambe quasi tese, scendi facendo scivolare il bilanciere lungo le cosce spingendo le anche indietro, schiena neutra. Risali contraendo glutei e femorali.",
  "Leg Extension": "Regola il cuscinetto sopra le caviglie. Estendi le gambe con controllo fino a contrarre il quadricipite, scendi frenando senza far cadere il pacco pesi.",
  "Leg Curl Sdraiato": "Cuscinetto sopra i talloni. Fletti le gambe portando i talloni verso i glutei senza sollevare il bacino, torna lento in allungamento.",
  "Hip Thrust": "Scapole appoggiate alla panca, bilanciere sul bacino. Spingi con i talloni ed estendi le anche fino ad allineare busto e cosce, contraendo forte i glutei in alto.",
  "Calf Raise in Piedi": "Avampiedi sul rialzo, talloni liberi. Sali il più in alto possibile sulle punte, pausa, scendi in massimo allungamento. Movimento lento e completo.",
  "Military Press": "In piedi, bilanciere alle clavicole, core e glutei contratti. Spingi in verticale portando la testa leggermente avanti a fine spinta. Non inarcare la zona lombare.",
  "Alzate Laterali": "Manubri ai fianchi, gomiti semiflessi. Solleva lateralmente fino all'altezza delle spalle guidando con i gomiti, scendi lento. Carichi leggeri, zero slanci.",
  "Arnold Press": "Parti con i manubri davanti alle spalle e palmi verso di te; spingendo in alto ruota i polsi fino ad avere i palmi in avanti. Torna ruotando in senso inverso.",
  "Face Pull": "Corda all'altezza del viso. Tira verso la fronte aprendo i gomiti in fuori e ruotando esternamente le spalle. Ottimo per la salute della cuffia.",
  "Curl Bilanciere": "In piedi, gomiti fermi ai fianchi. Fletti gli avambracci portando il bilanciere alle spalle senza oscillare il busto, scendi in 2-3 secondi.",
  "Hammer Curl": "Come il curl ma con presa neutra (palmi che si guardano). Colpisce brachiale e avambraccio. Gomiti fissi, discesa controllata.",
  "Curl Panca Scott": "Braccia appoggiate sul cuscino inclinato. Fletti fino in alto e scendi quasi a braccia distese senza mai perdere tensione. Isola il bicipite eliminando lo slancio.",
  "Pushdown Tricipiti": "Alla poulie alta, gomiti bloccati ai fianchi. Estendi gli avambracci fino in basso contraendo il tricipite, risali frenando fino ai 90°.",
  "French Press": "Sdraiato, bilanciere EZ sopra la fronte. Piega solo i gomiti scendendo verso la testa e riestendi. Gomiti stretti e fermi per tutto il movimento.",
  "Panca Presa Stretta": "Come la panca piana ma con presa alla larghezza spalle e gomiti vicini al corpo. Il carico si sposta sui tricipiti.",
  "Plank": "Avambracci a terra, corpo in linea, addome e glutei contratti. Non far cadere il bacino né alzarlo. Respira e mantieni la posizione per il tempo previsto.",
  "Crunch": "Sdraiato, gambe piegate, mani alle tempie. Solleva le scapole arrotondando la parte alta della schiena, espira contraendo l'addome, scendi lento.",
  "Leg Raise": "Sdraiato, mani sotto i glutei. Solleva le gambe tese fino alla verticale e scendile lente senza toccare terra, schiena lombare sempre aderente.",
  "Russian Twist": "Seduto con busto inclinato indietro e gambe sollevate. Ruota il busto da un lato all'altro toccando terra accanto al fianco, con o senza peso.",
  "Corsa": "Postura eretta, sguardo avanti, appoggio sotto il baricentro. Mantieni un ritmo in cui riesci a parlare a frasi corte (fondo lento) o spingi a intervalli per l'alta intensità. Aumenta il volume gradualmente.",
  "Tapis Roulant": "Imposta velocità o pendenza adatte al tuo livello, non aggrapparti ai corrimano. Camminata in salita (5-10%) è un'ottima alternativa a basso impatto.",
  "Cyclette": "Regola la sella all'altezza dell'anca: gamba quasi distesa nel punto più basso. Cadenza fluida 70-90 rpm, resistenza tale da mantenere lo sforzo costante.",
  "Vogatore": "Sequenza: spinta gambe → apertura busto → tirata braccia; ritorno in ordine inverso. La forza viene per il 60% dalle gambe. Schiena neutra sempre.",
  "Salto della Corda": "Salta basso sull'avampiede, polsi che ruotano la corda, gomiti vicini al corpo. Ottimo per condizionamento: alterna round da 1-3 minuti a pause brevi.",
  "Panca Piana Smith Machine": "Il bilanciere guidato stabilizza la traiettoria: posiziona la panca in modo che la barra scenda a metà petto. Scendi controllato e spingi senza bloccare i gomiti. Inserisci i fermi di sicurezza.",
  "Panca Inclinata Smith Machine": "Panca a 30-45° sotto la barra guidata, che deve scendere verso la parte alta del petto. Traiettoria fissa: concentrati sulla spinta e sul controllo della discesa.",
  "Croci Cavi dal Basso": "Cavi in basso, presa alle maniglie, busto leggermente avanti. Porta le mani in alto e verso il centro come ad abbracciare, stringendo il petto in alto. Enfatizza la porzione clavicolare.",
  "Croci Cavi dall'Alto": "Cavi in alto, passo avanti con un piede. Porta le mani in basso e verso il centro con gomiti semiflessi, stringendo il petto a fine movimento. Torna lento in apertura.",
  "Croci Manubri su Inclinata": "Su panca a 30-45°, apri i manubri ad arco con gomiti semiflessi fino ad allungare la parte alta del petto, poi richiudi. Carichi moderati e discesa controllata.",
  "Dip Machine": "Regola il sedile e le imbottiture. Spingi le maniglie verso il basso fino a estendere quasi i gomiti, controlla la risalita. Busto leggermente avanti per il petto, più verticale per i tricipiti.",
  "Push-Up Zavorrati": "Come il push-up classico ma con un disco sulla schiena (o zaino carico). Corpo sempre in linea, scendi completo e spingi senza inarcare la zona lombare.",
  "Chest Press Presa Stretta": "Alla chest press con presa stretta e gomiti vicini al corpo: sposta il lavoro su tricipiti e parte interna del petto. Non bloccare i gomiti a fine spinta.",
  "Panca Piana con Fermi": "Configura i fermi di sicurezza all'altezza del petto: ti permettono di spingere al limite in sicurezza anche da solo. Esecuzione identica alla panca piana classica.",
  "Pull-Up Assistito": "Alla macchina (o con elastico), il contrappeso riduce il peso da sollevare. Esecuzione come le trazioni: petto alla sbarra, gomiti in basso, discesa completa controllata.",
  "Lat Machine Presa Inversa": "Presa supina alla larghezza spalle. Tira la sbarra verso la parte alta del petto portando i gomiti in basso lungo i fianchi: maggiore enfasi su bicipiti e gran dorsale basso.",
  "Rematore Chest Support": "Petto appoggiato alla panca inclinata, manubri sospesi. Tira verso i fianchi stringendo le scapole: il supporto elimina lo slancio e scarica la zona lombare.",
  "Rematore Smith Machine": "Busto inclinato ~45°, tira la barra guidata verso l'ombelico con gomiti vicini al corpo. La traiettoria fissa aiuta a isolare il dorso: stringi le scapole a fine tirata.",
  "Rematore Pendlay": "Come il rematore ma esplosivo e senza appoggio: ogni ripetizione riparte da fermo a terra, schiena parallela al pavimento. Carichi più bassi, tecnica rigorosa.",
  "Pullover Manubrio": "Sdraiato traverso sulla panca, manubrio sopra il petto a braccia quasi tese. Scendi dietro la testa ad arco fino ad allungare il gran dorsale, risali usando il dorso, non le braccia.",
  "Pullover ai Cavi": "Alla poulie alta, a qualche passo di distanza, braccia quasi tese. Porta la sbarra verso le anche ad arco contraendo il gran dorsale, torna lento in allungamento.",
  "Rack Pull": "Stacco accorciato dai fermi del rack (sotto o sopra il ginocchio). Schiena neutra, spingi il pavimento con le gambe e chiudi le anche. Sovraccarica la parte alta dello stacco.",
  "Good Morning": "Bilanciere sui trapezi, gambe quasi tese. Scendi spingendo le anche indietro con schiena neutra fino al busto quasi parallelo, risali contraendo glutei e femorali. Carichi leggeri.",
  "Trazioni Presa Larga": "Presa prona molto larga. Tira il petto verso la sbarra pensando a portare i gomiti verso i fianchi: massima enfasi sul gran dorsale, meno coinvolgimento dei bicipiti.",
  "Squat Smith Machine": "Bilanciere guidato sui trapezi, piedi leggermente avanti rispetto alla barra. Scendi fino a cosce parallele spingendo le anche indietro, risali spingendo con tutto il piede.",
  "Goblet Squat": "Manubrio o kettlebell tenuto al petto. Scendi profondo tra le ginocchia tenendo il busto eretto e i talloni a terra. Ottimo per imparare lo schema dello squat.",
  "Stacco Sumo": "Stacco con piedi molto larghi e punte in fuori, mani tra le gambe. Busto più verticale: più enfasi su glutei e adduttori, meno sulla zona lombare. Spingi il pavimento in fuori.",
  "Affondi in Camminata": "Affondo dinamico in avanzamento: passo lungo, scendi in verticale finché il ginocchio posteriore sfiora terra, poi spingi e porta avanti l'altra gamba. Core attivo e busto eretto.",
  "Leg Curl in Piedi": "Alla macchina in piedi, un arto alla volta: fletti il tallone verso il gluteo senza muovere l'anca, stringi il femorale in alto e scendi controllato.",
  "Adductor Machine": "Seduto, gambe divaricate contro le imbottiture. Chiudi le gambe contraendo gli adduttori, riapri frenando il carico senza far sbattere il pacco pesi.",
  "Abductor Machine": "Seduto, gambe chiuse. Spingi le ginocchia in fuori contraendo glutei medi, torna controllato. Busto fermo, niente slanci.",
  "Glute Bridge": "Sdraiato, piedi a terra vicino ai glutei. Spingi il bacino in alto contraendo forte i glutei fino ad allineare spalle-anche-ginocchia, pausa in cima, scendi lento. Si può caricare con un disco.",
  "Box Step-Up": "Un piede intero sul box, spingi con il tallone fino a estendere la gamba senza darti slancio con l'altra. Scendi controllato. Più alto il box, più lavorano glutei e femorali.",
  "Calf Raise alla Pressa": "Alla leg press con le punte dei piedi sul bordo della pedana. Estendi le caviglie spingendo sulle punte, pausa in alto, scendi in massimo allungamento. Gambe ferme.",
  "Squat con Fermi": "Squat dentro il rack con fermi di sicurezza regolati appena sotto la tua profondità: puoi spingere al limite in sicurezza senza partner. Esecuzione come lo squat classico.",
  "Military Press Seduto": "Seduto su panca con schienale, bilanciere alle clavicole. Spingi in verticale senza inarcare la zona lombare (lo schienale aiuta) e scendi controllato.",
  "Shoulder Press Machine": "Regola il sedile con le maniglie all'altezza delle spalle. Spingi in alto senza bloccare i gomiti e scendi lento fino a ~90°. Traiettoria guidata, ottima per spingere al limite.",
  "Alzate Laterali Macchina": "Avambracci contro le imbottiture, gomiti che guidano il movimento. Solleva lateralmente fino all'altezza delle spalle e scendi frenando. Tensione costante sui deltoidi.",
  "Alzate Laterali Seduto": "Seduto, manubri ai fianchi. Solleva lateralmente guidando con i gomiti fino all'altezza delle spalle: la posizione seduta elimina lo slancio delle gambe.",
  "Reverse Pec Deck": "Seduto di fronte alla macchina, petto contro l'imbottitura. Apri le braccia all'indietro contraendo i deltoidi posteriori e le scapole, torna lento. Carichi leggeri.",
  "Tirate al Mento": "Presa stretta sul bilanciere, tira in alto lungo il corpo guidando con i gomiti fino al petto. Fermati se avverti fastidio alle spalle; alternativa più sicura: presa più larga.",
  "Alzate Frontali ai Cavi": "Alla poulie bassa, di spalle al cavo. Solleva la corda o la maniglia davanti a te fino all'altezza delle spalle, braccio quasi teso, scendi controllato.",
  "Shrug Manubri": "Manubri ai fianchi, braccia tese. Solleva le spalle verso le orecchie contraendo i trapezi, pausa in alto, scendi lento. Niente rotazioni delle spalle.",
  "Curl Bilanciere EZ": "Come il curl con bilanciere ma con la barra sagomata EZ: polsi in posizione più naturale, meno stress articolare. Gomiti fermi ai fianchi, discesa in 2-3 secondi.",
  "Curl su Panca Inclinata": "Seduto su panca a 45-60°, braccia che pendono dietro il busto. Fletti i manubri senza muovere le spalle: massimo allungamento del bicipite in basso.",
  "Curl Macchina": "Avambracci sulla imbottitura, impugna le maniglie. Fletti completamente contraendo il bicipite e torna lento quasi a braccia distese. La macchina mantiene tensione costante.",
  "Curl Presa Inversa": "Curl con presa prona (dorso delle mani in alto). Carichi molto più leggeri del solito: colpisce brachioradiale e avambracci. Gomiti fermi, polsi dritti.",
  "Zottman Curl": "Sali in curl con presa supina, in alto ruota i polsi in prono e scendi lento con presa inversa. Combina bicipite in salita e avambracci in discesa.",
  "Hammer Curl ai Cavi": "Alla poulie bassa con la corda, presa neutra. Fletti portando le estremità della corda verso le spalle, gomiti fermi. Tensione continua su brachiale e avambraccio.",
  "French Press Manubri": "Sdraiato o seduto, un manubrio a due mani sopra la testa. Piega solo i gomiti scendendo dietro la nuca e riestendi contraendo il tricipite. Gomiti stretti e fermi.",
  "Pushdown Presa Inversa": "Alla poulie alta con presa supina. Estendi gli avambracci in basso tenendo i gomiti bloccati ai fianchi: enfasi sul capo mediale del tricipite. Carichi leggeri.",
  "Pushdown Braccio Singolo": "Pushdown con una maniglia, un braccio alla volta. Gomito bloccato al fianco, estendi completamente e stringi un secondo in basso. Correggi eventuali squilibri tra i lati.",
  "Kickback ai Cavi": "Alla poulie bassa, busto inclinato avanti, gomito alto e fermo. Estendi il braccio all'indietro fino a contrarre il tricipite, torna controllato. Niente oscillazioni.",
  "Estensione Singola Sopra la Testa": "Un manubrio tenuto a una mano sopra la testa, gomito vicino all'orecchio e fermo. Scendi dietro la nuca piegando solo il gomito e riestendi. Massimo allungamento del capo lungo.",
  "Dip Machine Tricipiti": "Alla dip machine con busto verticale e gomiti stretti: spingi le maniglie in basso concentrandoti sull'estensione del gomito per isolare i tricipiti.",
  "Crunch Inverso": "Sdraiato, gambe piegate sollevate. Arrotola il bacino verso il petto sollevando i glutei da terra contraendo l'addome, scendi lento. Non dondolare le gambe.",
  "Crunch su Panca Declinata": "Sulla panca declinata con le gambe bloccate. Solleva le scapole arrotondando la schiena alta, espira in contrazione. Rom aumentato: attenzione al controllo della discesa.",
  "Sit-Up": "Sdraiato, gambe piegate e piedi fermi. Sali con tutto il busto arrotolando la schiena, espira in cima, scendi controllato vertebra dopo vertebra. Non tirare il collo con le mani.",
  "Mountain Climbers": "In plank sulle mani, porta le ginocchia al petto alternando le gambe a ritmo sostenuto. Bacino basso e stabile, addome contratto. Core e condizionamento insieme.",
  "Dead Bug": "Sdraiato, braccia in verticale e gambe a tavolino. Distendi braccio e gamba opposti verso terra tenendo la zona lombare incollata al pavimento, torna e cambia lato.",
  "Hollow Hold": "Sdraiato, solleva scapole e gambe tenendo la zona lombare a terra, corpo a 'banana'. Addome contratto forte, respira. Mantieni la posizione per il tempo previsto.",
  "Toes to Bar": "Appeso alla sbarra, porta le punte dei piedi alla sbarra sollevando le gambe con l'addome, scendi controllato senza slancio. Versione ridotta: ginocchia al petto.",
  "Pallof Press": "Alla poulie (o con elastico) laterale al busto, mani al petto. Spingi le mani in avanti resistendo alla rotazione del busto, pausa, torna. Anti-rotazione per il core.",
  "Ab Crunch Machine": "Seduto, avambracci o spalle contro l'imbottitura. Fletti il busto arrotolando la schiena contraendo l'addome, torna frenando il carico. Espira in contrazione.",
  "V-Up": "Sdraiato, braccia oltre la testa. Solleva contemporaneamente busto e gambe tese formando una V, tocca le punte, scendi controllato. Addome sempre contratto.",
  "Camminata in Salita": "Su tapis roulant a pendenza 5-15%: ottimo cardio a basso impatto che attiva glutei e polpacci. Non aggrapparti ai corrimano, mantieni un passo sostenuto.",
  "Sprint": "Scatti brevi ad alta intensità (10-30 secondi) alternati a recupero camminato. Riscaldati bene prima: il lavoro si svolge negli intervalli, non a ritmo continuo.",
  "Nuoto": "Ottimo cardio a impatto zero su tutto il corpo. Alterna stili e ritmi: serie a ritmo moderato con recuperi brevi per lavoro aerobico continuo.",
  "Assault Bike": "Bike con ventola: più spingi forte, più la resistenza aumenta. Ideale per intervalli intensi (es. 20\" sprint / 40\" facile). Gambe e braccia spingono insieme.",
  "Spin Bike": "Bike da spinning con resistenza regolabile. Cadenza 80-100 rpm, alterna tratti seduti e in piedi. Regola sella e manubrio prima di partire.",
  "Burpees": "Da in piedi: piegati, mani a terra, salto in plank, piegamento, ritorno e salto in alto. Cardio a corpo libero totale: gestisci il ritmo per non bruciarti subito.",
  "Jumping Jack": "Saltelli aprendo e chiudendo gambe e braccia. Semplice ed efficace per alzare la frequenza cardiaca: usalo a blocchi da 1-3 minuti.",
  "Sacco da Boxe": "Combinazioni di pugni al sacco a round da 2-3 minuti con 1 minuto di recupero. Colpisci con tecnica, resta leggero sulle gambe e continua a muoverti tra un colpo e l'altro.",
  "Battle Ropes": "Onde con le funi: braccia alternate o insieme, busto stabile e core contratto. Round da 20-40 secondi ad alta intensità con recuperi brevi.",
  "Rear Deltoid": "Esercizio per i deltoidi posteriori (ai cavi, manubri o macchina). Gomiti leggermente flessi, apri le braccia all'indietro guidando con i gomiti fino ad allineare le spalle, focalizzandoti sul capo posteriore del deltoide.",
  "Rear Delt Fly": "Busto inclinato a 45° o su panca inclinata, apri le braccia a croce verso l'esterno senza addurre eccessivamente le scapole. Mantieni tensione costante sui deltoidi posteriori.",
  "Lu Raises": "Partendo con i manubri davanti al bacino, solleva lateralmente fino a portare i manubri sopra la testa in un movimento circolare continuo. Rinforza deltoidi laterali e trapezi.",
  "Y-Raise": "Su panca inclinata a 30-45°, solleva i manubri formando una Y a braccia distese e pollici verso l'alto. Ottimo per deltoide posteriore e trapezio inferiore.",
  "Seated Row": "Seduto alla macchina o al cavo orizzontale, mantieni il busto eretto con petto in fuori. Tira l'impugnatura verso l'addome portando i gomiti indietro e stringendo le scapole, torna controllato in allungamento.",
  "Lat Machine Presa Neutra": "Tirata alla lat machine con impugnatura a V (triangolo) o barra a prese parallele. Gomiti aderenti al corpo, tira verso il petto enfatizzando la parte centrale e bassa del gran dorsale.",
  "Seal Row": "Sdraiato prono su una panca orizzontale rialzata, bilanciere o manubri sospesi. Tira verso il basso del torace stringendo le scapole: azzera ogni compenso o slancio lombare.",
  "Meadows Row": "In piedi di lato a un bilanciere inserito nel landmine, presa prona sull'estremità della barra. Tira guidando con il gomito verso l'alto e indietro per un lavoro dorsale asimmetrico intenso.",
  "Lat Prayer": "Inginocchiato davanti alla poulie alta con corda, braccia tese. Spingi la corda verso le ginocchia disegnando un arco con il corpo inclinato, isolando il gran dorsale.",
  "Chest Fly Macchina": "Seduto alla pectoral/fly machine con schiena aderente. Porta le maniglie verso il centro stringendo i pettorali a fine corsa con gomiti leggermente piegati, controlla la fase di apertura.",
  "Floor Press": "Sdraiato a terra con bilanciere o manubri. Scendi finché i tricipiti toccano delicatamente il pavimento a 90°, pausa di mezzo secondo e spingi in alto. Protegge le spalle ed esalta la chiusura del tricipite.",
  "Croci ai Cavi su Panca": "Panca posizionata al centro dei cavi. Esegui il movimento di apertura ad arco fino a sentire l'allungamento del petto, poi richiudi al centro con tensione costante garantita dai cavi.",
  "Stacco Rumeno con Manubri": "In piedi con manubri davanti alle cosce, ginocchia leggermente flesse. Spingi il bacino indietro facendo scivolare i manubri lungo le tibie con schiena neutra, risali contraendo glutei e femorali.",
  "Bulgarian Split Squat Smith Machine": "Piede posteriore appoggiato su panca, barra guidata sui trapezi. Scendi in verticale fino a portare la coscia anteriore parallela a terra, spingi con il tallone anteriore.",
  "Belt Squat": "Squat con sovraccarico agganciato alla cintura tramite cavo o perno: permette di allenare le gambe ad alto carico senza alcun carico assiale sulla colonna vertebrale.",
  "Sissy Squat": "Fletti le ginocchia portandole in avanti mentre inclini il busto all'indietro in linea con le cosce. Isola in modo estremo i quadricipiti con il solo peso corporeo o leggero disco.",
  "Nordic Hamstring Curl": "Inginocchiato con caviglie bloccate, scendi lentamente in avanti resistendo con la forza dei muscoli ischiocrurali. Esercizio eccentrico fondamentale per la prevenzione infortuni.",
  "Wall Sit": "Schiena contro la parete, cosce parallele al pavimento a 90°, ginocchia sopra le caviglie. Mantieni la posizione isometrica per il tempo stabilito, respirando con regolarità.",
  "Bayesian Curl": "Di spalle alla poulie bassa, cavo che parte da dietro. Fletti il gomito portando la mano verso la spalla partendo da una posizione di pre-allungamento del bicipite dietro al busto.",
  "Preacher Curl Manubri": "Un braccio alla volta sul cuscino della panca Scott. Fletti il manubrio verso la spalla e scendi controllato fino a quasi distendere il braccio senza iperestendere il gomito.",
  "Drag Curl": "Fletti le braccia facendo scivolare il bilanciere o i manubri lungo il torace, portando i gomiti all'indietro invece che avanti. Elimina il lavoro del deltoide anteriore focalizzandosi sul bicipite.",
  "Skull Crusher": "Sdraiato su panca con bilanciere EZ, braccia leggermente inclinate all'indietro. Piega i gomiti portando la barra verso la fronte o la sommità del capo, poi riestendi completamente.",
  "Overhead Cable Extension": "Di spalle alla poulie alta con la corda sopra la testa. Spingi la corda in avanti-alto fino alla distensione completa dei gomiti aprendo le estremità, ottimo per il capo lungo del tricipite.",
  "JM Press": "Su panca piana con bilanciere, scendi portando la barra verso il mento/collo piegando i gomiti e mantenendoli a 45°, poi spingi estendendo con forza i tricipiti.",
  "Tate Press": "Sdraiato con manubri sul petto, gomiti in fuori. Estendi gli avambracci ruotando i manubri verso l'alto fino a distendere le braccia, isolando la porzione distale dei tricipiti.",
  "Bicycle Crunch": "Sdraiato a terra, mani alla nuca. Porta alternativamente il gomito destro verso il ginocchio sinistro e viceversa, distendendo la gamba opposta a ritmo continuo.",
  "Hanging Knee Raise": "Appeso alla sbarra, solleva le ginocchia verso il petto arrotolando il bacino verso l'alto senza dondolare con il corpo, scendi lento.",
  "Cable Woodchopper": "Alla poulie alta o bassa, ruota il busto tirando il cavo in diagonale attraverso il corpo contraendo gli addominali obliqui e il core.",
  "Dragon Flag": "Sdraiato su panca afferrando i bordi dietro la testa. Solleva l'intero corpo rigido come una tavola facendo perno solo sulle scapole, scendi il più lentamente possibile.",
  "SkiErg": "Simulatore di sci di fondo: afferra le maniglie in alto, piega le braccia e spingi verso il basso flettendo anche busto e ginocchia con un movimento ritmico e potente.",
  "Stairmaster": "Camminata continua su gradini motorizzati: mantieni il busto eretto, non appoggiarti pesantemente sui corrimano e spingi a fondo con tutto il piede per coinvolgere glutei e polpacci.",
};
export const INFO_FALLBACK = {
  Petto: "Esercizio per il pettorale: scapole addotte, movimento controllato in discesa e spinta senza bloccare i gomiti. Concentrati sul sentire lavorare il petto, non solo braccia e spalle.",
  Dorso: "Esercizio di tirata per il dorso: parti da braccia distese, tira guidando con i gomiti (non con le mani) e stringi le scapole a fine movimento. Torna in allungamento frenando il carico.",
  Gambe: "Esercizio per la parte inferiore: schiena neutra, ginocchia in linea con le punte dei piedi, scendi controllato e spingi con tutto il piede. La profondità corretta vale più del carico.",
  Spalle: "Esercizio per i deltoidi: carichi moderati, niente slanci, movimento guidato dai gomiti. Ferma l'alzata all'altezza delle spalle e scendi lentamente.",
  Bicipiti: "Esercizio di flessione per i bicipiti: gomiti fermi vicino al busto, sali contraendo e scendi in 2-3 secondi senza oscillare il corpo.",
  Tricipiti: "Esercizio di estensione per i tricipiti: gomiti bloccati e vicini al corpo, estendi completamente contraendo e risali frenando il carico.",
  Core: "Esercizio per il core: bacino stabile, zona lombare protetta, movimento lento guidato dall'addome con espirazione nella fase di contrazione.",
  Cardio: "Attività aerobica: mantieni un ritmo sostenibile e costante, monitora respiro o frequenza cardiaca, e incrementa durata o intensità in modo graduale settimana dopo settimana.",
  Altro: "Esegui il movimento in modo lento e controllato, con postura corretta e senza compensi. Se non conosci la tecnica, chiedi una dimostrazione al trainer della tua palestra.",
};

/* ---------------- Mapping import → database esercizi ---------------- */
/* Cerca la corrispondenza migliore col DB; il testo in eccesso del titolo finisce nelle note */
export const ALL_EXERCISES = Object.values(EXERCISE_DB).flat();
export const normalizeEx = (s) => s.toLowerCase().replace(/[^a-zà-ù0-9 ]/gi, " ").replace(/\s+/g, " ").trim();
export const matchToDb = (title) => {
  const t = normalizeEx(title);
  let best = null;
  for (const list of Object.values(EXERCISE_DB)) {
    for (const dbEx of list) {
      const d = normalizeEx(dbEx);
      if (t === d) return { name: dbEx, note: "" };
      if ((t.startsWith(d + " ") || t.includes(" " + d + " ") || t.endsWith(" " + d)) &&
          (!best || d.length > normalizeEx(best).length)) best = dbEx;
    }
  }
  if (best) {
    const note = title.replace(new RegExp(best.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"), "")
      .replace(/^[\s\-–—·,:]+|[\s\-–—·,:]+$/g, "");
    return { name: best, note };
  }
  return { name: title, note: "" };
};



export const EXERCISE_MEDIA = {
  "Ab Crunch Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Crunch_Machine/0.jpg",
  "Ab Wheel": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/0.jpg",
  "Abductor Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/0.jpg",
  "Adductor Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Adductor/0.jpg",
  "Affondi Bulgari": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Leg_Barbell_Squat/0.jpg",
  "Affondi in Camminata": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Walking_Lunge/0.jpg",
  "Affondi Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg",
  "Alzate Frontali": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg",
  "Alzate Frontali ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Low-Pulley_Deltoid_Raise/0.jpg",
  "Alzate Laterali": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg",
  "Alzate Laterali ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Seated_Lateral_Raise/0.jpg",
  "Alzate Laterali Macchina": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Seated_Lateral_Raise/0.jpg",
  "Alzate Laterali Seduto": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Side_Lateral_Raise/0.jpg",
  "Alzate Posteriori": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Bent-Over_Rear_Delt_Raise/0.jpg",
  "Arnold Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg",
  "Assault Bike": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Air_Bike/0.jpg",
  "Battle Ropes": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battling_Ropes/0.jpg",
  "Box Step-Up": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg",
  "Calf Raise alla Pressa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/0.jpg",
  "Calf Raise in Piedi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg",
  "Calf Raise Seduto": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg",
  "Camminata in Salita": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking_Treadmill/0.jpg",
  "Camminata Veloce": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking_Treadmill/0.jpg",
  "Chest Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/0.jpg",
  "Chest Press Presa Stretta": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_EZ-Bar_Press/0.jpg",
  "Corsa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running_Treadmill/0.jpg",
  "Croci ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg",
  "Croci Cavi dal Basso": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Low_Cable_Crossover/0.jpg",
  "Croci Cavi dall'Alto": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg",
  "Croci Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg",
  "Croci Manubri su Inclinata": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg",
  "Crunch": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg",
  "Crunch ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg",
  "Crunch Inverso": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Crunch/0.jpg",
  "Crunch su Panca Declinata": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Crunch/0.jpg",
  "Curl ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Biceps_Cable_Curl/0.jpg",
  "Curl Bilanciere": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg",
  "Curl Bilanciere EZ": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg",
  "Curl Concentrato": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg",
  "Curl Macchina": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bicep_Curl/0.jpg",
  "Curl Manubri Alternato": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Alternate_Bicep_Curl/0.jpg",
  "Curl Panca Scott": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg",
  "Curl Presa Inversa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Reverse_Curl/0.jpg",
  "Curl su Panca Inclinata": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg",
  "Cyclette": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycling_Stationary/0.jpg",
  "Dead Bug": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg",
  "Dip alle Parallele": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Parallel_Bar_Dip/0.jpg",
  "Dip Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dip_Machine/0.jpg",
  "Dip Machine Tricipiti": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dip_Machine/0.jpg",
  "Dip tra Panche": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg",
  "Ellittica": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical_Trainer/0.jpg",
  "Estensione Singola Sopra la Testa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_One-Arm_Triceps_Extension/0.jpg",
  "Estensioni Sopra la Testa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/0.jpg",
  "Face Pull": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg",
  "French Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/0.jpg",
  "French Press Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Triceps_Extension/0.jpg",
  "Front Squat": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg",
  "Glute Bridge": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg",
  "Goblet Squat": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg",
  "Good Morning": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg",
  "Hack Squat": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg",
  "Hammer Curl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg",
  "Hammer Curl ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hammer_Curls_-_Rope_Attachment/0.jpg",
  "Hanging Leg Raise": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg",
  "Hip Thrust": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg",
  "Hyperextension": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/0.jpg",
  "Kickback ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Low-Pulley_One-Arm_Triceps_Extension/0.jpg",
  "Kickback Manubrio": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/0.jpg",
  "Lat Machine Avanti": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg",
  "Lat Machine Presa Inversa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Underhand_Cable_Pulldowns/0.jpg",
  "Lat Machine Presa Stretta": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg",
  "Leg Curl in Piedi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Leg_Curl/0.jpg",
  "Leg Curl Sdraiato": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg",
  "Leg Curl Seduto": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg",
  "Leg Extension": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg",
  "Leg Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg",
  "Leg Raise": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Lying_Leg_Raise/0.jpg",
  "Military Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg",
  "Military Press Seduto": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Barbell_Military_Press/0.jpg",
  "Mountain Climbers": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/0.jpg",
  "Pallof Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/0.jpg",
  "Panca Declinata": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/0.jpg",
  "Panca Inclinata Bilanciere": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg",
  "Panca Inclinata Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg",
  "Panca Inclinata Smith Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Incline_Bench_Press/0.jpg",
  "Panca Piana Bilanciere": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg",
  "Panca Piana con Fermi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Press_-_Powerlifting/0.jpg",
  "Panca Piana Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg",
  "Panca Piana Smith Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Bench_Press/0.jpg",
  "Panca Presa Stretta": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg",
  "Pectoral Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.jpg",
  "Plank": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg",
  "Pull-Down Braccia Tese": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg",
  "Pull-Up Assistito": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg",
  "Pulley Basso": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg",
  "Pullover ai Cavi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg",
  "Pullover Manubrio": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg",
  "Push-Up": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg",
  "Push-Up Zavorrati": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg",
  "Pushdown Braccio Singolo": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_One_Arm_Tricep_Extension/0.jpg",
  "Pushdown Corda": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg",
  "Pushdown Presa Inversa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Triceps_Pushdown/0.jpg",
  "Pushdown Tricipiti": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg",
  "Rack Pull": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rack_Pulls/0.jpg",
  "Rematore Bilanciere": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg",
  "Rematore Chest Support": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Incline_Row/0.jpg",
  "Rematore Manubrio": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg",
  "Rematore Pendlay": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg",
  "Rematore Smith Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Bent_Over_Row/0.jpg",
  "Rematore T-Bar": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row_with_Handle/0.jpg",
  "Reverse Pec Deck": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rear_Delt_Fly/0.jpg",
  "Russian Twist": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg",
  "Salto della Corda": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Fast_Skipping/0.jpg",
  "Shoulder Press Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/0.jpg",
  "Shoulder Press Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg",
  "Shrug Bilanciere": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg",
  "Shrug Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shrug/0.jpg",
  "Side Plank": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Bridge/0.jpg",
  "Sit-Up": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sit-Up/0.jpg",
  "Spider Curl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spider_Curl/0.jpg",
  "Spin Bike": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Recumbent_Bike/0.jpg",
  "Sprint": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running_Treadmill/0.jpg",
  "Squat Bilanciere": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg",
  "Squat con Fermi": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg",
  "Squat Smith Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Squat/0.jpg",
  "Stacco da Terra": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg",
  "Stacco Rumeno": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg",
  "Stacco Sumo": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg",
  "Stepper": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stairmaster/0.jpg",
  "Tapis Roulant": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking_Treadmill/0.jpg",
  "Tirate al Mento": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg",
  "Toes to Bar": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg",
  "Trazioni": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg",
  "Trazioni Presa Inversa": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg",
  "Trazioni Presa Larga": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg",
  "V-Up": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jackknife_Sit-Up/0.jpg",
  "Vogatore": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Stationary/0.jpg",
  "Zottman Curl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Zottman_Curl/0.jpg",
  "Rear Deltoid": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Bent-Over_Rear_Delt_Raise/0.jpg",
  "Rear Delt Fly": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rear_Delt_Fly/0.jpg",
  "Lu Raises": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg",
  "Y-Raise": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg",
  "Seated Row": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg",
  "Lat Machine Presa Neutra": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Bar_Pulldown/0.jpg",
  "Seal Row": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Incline_Row/0.jpg",
  "Meadows Row": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg",
  "Lat Prayer": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Low-Pulley_Deltoid_Raise/0.jpg",
  "Chest Fly Macchina": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.jpg",
  "Floor Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Floor_Press/0.jpg",
  "Croci ai Cavi su Panca": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg",
  "Stacco Rumeno con Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg",
  "Bulgarian Split Squat Smith Machine": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Leg_Barbell_Squat/0.jpg",
  "Belt Squat": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg",
  "Sissy Squat": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Sissy_Squat/0.jpg",
  "Nordic Hamstring Curl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg",
  "Wall Sit": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wall_Squat/0.jpg",
  "Bayesian Curl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Biceps_Cable_Curl/0.jpg",
  "Preacher Curl Manubri": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg",
  "Drag Curl": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg",
  "Skull Crusher": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Triceps_Extension/0.jpg",
  "Overhead Cable Extension": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/0.jpg",
  "JM Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_EZ-Bar_Press/0.jpg",
  "Tate Press": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_One-Arm_Triceps_Extension/0.jpg",
  "Bicycle Crunch": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Air_Bike/0.jpg",
  "Hanging Knee Raise": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg",
  "Cable Woodchopper": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg",
  "Dragon Flag": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Crunch/0.jpg",
  "SkiErg": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Fast_Skipping/0.jpg",
  "Stairmaster": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stairmaster/0.jpg",
};

const HOLD_RE = /plank|hollow hold|wall sit/i;
export const isHold = (name) => HOLD_RE.test(name || "");
export const exMode = (ex) => ex.mode || (isHold(ex.name) ? "hold" : undefined);
export const holdSets = (n = 3, sec = 60) => Array.from({ length: n }, () => ({ sec, elapsed: 0, done: false }));
/* Esercizi con manubri: il peso inserito e' quello del SINGOLO manubrio */
export const isDumbbell = (name) => /manubri|manubrio/i.test(name || "");
