export const TROPHIES = [
  {
    id: "recruit",
    name: "Medaglia del Reclutamento",
    rarity: "comune",
    how: "Si ottiene all'iscrizione: il primo passo nel programma.",
    lore: "Coniata nella Fucina dei Precursori prima che i mondi avessero nome, questa medaglia reca il sigillo di GYMQUEST inciso nell'oro antico. La leggenda narra che i Saggi la consegnassero a ogni viaggiatore che varcasse la soglia dell'addestramento: al centro pulsa un frammento di Eco puro, sigillato nel metallo, che si risveglia a ogni passo del suo portatore. Non è una ricompensa. È un giuramento.",
    check: () => true,
    model: "recruit",
  },
  {
    id: "firstw",
    name: "Manubrio del Battesimo",
    rarity: "comune",
    how: "Completa il tuo primo allenamento.",
    lore: "Si dice che il primo manubrio forgiato dai Precursori fosse troppo pesante per qualunque mortale. Fu un apprendista, con mani tremanti e orgoglio incrollabile, a sollevarlo per primo. Da allora, chi completa il primo allenamento riceve questa replica in bronzo: piccola, sbiadita, e vale più di qualsiasi tesoro — perché segna il momento esatto in cui il viaggio è iniziato.",
    check: (s) => s.workouts >= 1,
    model: "firstw",
  },
  {
    id: "orb5",
    name: "Sfera del Precursore",
    rarity: "raro",
    how: "Raggiungi il livello 5.",
    lore: "Recuperata tra le rovine sommerse di Mar, questa sfera fluttua ancora dopo millenni, attraversata da venature di Eco verde che pulsano come un cuore addormentato. I Precursori le usavano come chiavi: aprivano porte che nessun altro popolo ha mai saputo richiudere. Averne una significa che le porte, da ora in poi, si apriranno anche per te.",
    check: (s, prs, lvl) => lvl >= 5,
    model: "orb5",
  },
  {
    id: "crystal10",
    name: "Cristallo d'Eco Verde",
    rarity: "raro",
    how: "Raggiungi il livello 10.",
    lore: "L'Eco verde è l'energia della crescita: la stessa che trasformò un ragazzo silenzioso in un eroe. Questo cristallo è cresciuto di un millimetro per ogni livello che hai conquistato, nutrito dalla tua fatica. I Saggi avvertono: non guardarlo troppo a lungo. Chi lo fa, giura di sentirlo sussurrare il proprio nome.",
    check: (s, prs, lvl) => lvl >= 10,
    model: "crystal10",
  },
  {
    id: "w50",
    name: "Kettlebell del Veterano",
    rarity: "raro",
    how: "Completa 50 allenamenti.",
    lore: "Cinquant'anni prima che le forge si spegnessero, i Precursori crearono attrezzi che si temperavano con l'uso, non con il fuoco. Questo kettlebell ha assorbito cinquanta sessioni del tuo sudore e ora porta sul guscio il sigillo incandescente di chi non si è mai fermato. Il metallo si ricorda di te.",
    check: (s) => s.workouts >= 50,
    model: "w50",
  },
  {
    id: "idol15",
    name: "Idolo del Saggio",
    rarity: "epico",
    how: "Raggiungi il livello 15.",
    lore: "Una statuetta votiva dei Saggi delle montagne, quelli che parlavano solo con chi dimostrava di meritarselo. Il suo occhio di Eco azzurro si accese l'ultima volta quando un erede del fato lo sfiorò — o almeno così dicono le cronache. Il livello quindici è la soglia in cui l'addestrato smette di essere recluta: l'Idolo ora veglia su di te.",
    check: (s, prs, lvl) => lvl >= 15,
    model: "idol15",
  },
  {
    id: "bench100",
    name: "Piatto dei Cento",
    rarity: "epico",
    how: "PR di 100 kg su Panca Piana Bilanciere.",
    lore: "Cento chilogrammi: il numero che separa chi si allena da chi è allenato. Questo disco d'oro massiccio è la replica esatta di quello custodito nella Palestra dei Cieli, dove i guerrieri Precursor misuravano il proprio valore. Non esiste sblocco più onesto di questo: il ferro non mente, non lusinga, non perdona. Tu l'hai sollevato.",
    check: (s, prs) => (prs?.["Panca Piana Bilanciere"] || 0) >= 100,
    model: "bench100",
  },
  {
    id: "odst600",
    name: "Elmo dell'ODST",
    rarity: "epico",
    how: "Accumula 600 minuti di cardio totali.",
    lore: "Seicento minuti di fiato, passi e battito. Gli ODST — i soldati che si lanciavano dal cielo dentro bare di metallo — dicevano che le gambe sono la prima arma e i polmoni la seconda. Questo elmo, con la visiera ancora carica di Eco azzurro, appartenne a un paracadutista che corse per tre giorni senza fermarsi. Ora è tuo. E le sue gambe, in un certo senso, anche.",
    check: (s) => s.cardioMin >= 600,
    model: "odst600",
  },
  {
    id: "pillar20",
    name: "Sigillo della Colonna",
    rarity: "epico",
    how: "Raggiungi il livello 20.",
    lore: "Le Colonne dei Precursori reggevano il cielo prima che esistessero le montagne, e al centro di ognuna brillava un sigillo d'Eco ambrato: il perno che teneva insieme pietra e destino. Al livello venti sei diventato esattamente questo — un perno. Costanza, disciplina, struttura. Il cielo, da qualche parte, si regge anche su di te.",
    check: (s, prs, lvl) => lvl >= 20,
    model: "pillar20",
  },
  {
    id: "q50",
    name: "Stella del Cacciatore",
    rarity: "epico",
    how: "Completa 50 quest.",
    lore: "Cinquanta contratti, cinquanta taglie riscosse. Nell'era dei Precursori i cacciatori di incarichi portavano una stella d'oro sul petto, e al centro di essa un tizzone d'Eco ambrato che non si spegneva mai — nemmeno sott'acqua, nemmeno nel buio più fitto. Dicevano: la stella non brilla per te. Brilla grazie a te.",
    check: (s) => s.questsDone >= 50,
    model: "q50",
  },
  {
    id: "mjolnir",
    name: "Martello Mjolnir",
    rarity: "leggendario",
    how: "Solleva 500.000 kg di volume totale.",
    lore: "Mezzo milione di chilogrammi spostati dal punto A al punto B, una ripetizione alla volta. Questo martello, gemello dell'armatura degli dèi della guerra moderna, risponde a una sola regola, antica come i Precursori: nessuno può sollevarlo se non ne è degno. I condensatori d'Eco azzurro ai lati non sono decorazione — sono la misura esatta della tua degnità.",
    check: (s) => s.volume >= 500000,
    model: "mjolnir",
  },
  {
    id: "crown25",
    name: "Corona Hyper Lethal",
    rarity: "leggendario",
    how: "Raggiungi il livello 25.",
    lore: "Nella mitologia militare, 'Hyper Lethal' è un vettore attribuito a due soli esseri in tutta la storia. Nella mitologia dei Precursori, la corona apparteneva a chi aveva trasceso l'addestramento per diventare leggenda vivente. La gemma magenta al centro è Eco puro condensato da venticinque livelli di disciplina. Indossarla non è un diritto. È una sentenza.",
    check: (s, prs, lvl) => lvl >= 25,
    model: "crown25",
  },
];

export const RARITY = {
  comune: { label: "COMUNE", color: "#6fb3d4", border: "#2a5f7d" },
  raro: { label: "RARO", color: "#57c8f2", border: "#1f6f9e" },
  epico: { label: "EPICO", color: "#c99df0", border: "#7a4fae" },
  leggendario: { label: "LEGGENDARIO", color: "#ffd76a", border: "#b8860b" },
};

export const unlockedTrophies = (stats, prs, level) =>
  TROPHIES.filter((t) => { try { return t.check(stats, prs, level); } catch { return false; } });
